### ISSUE TITLE
Make codebase maintainable: add type hinting and code formatting

### ISSUE THREAD

**Issue by c-shubh** [tyiop794/BibliograPy#11]
I would like to add type hints to methods and variables, add docstrings and format the code to be consistent with [black](https://pypi.org/project/black/).

Addition of type hints would help in making the code more readable by stating the types upfront rather than the developer having to figure it out by themselves looking at nearby code.

**Comment by c-shubh** [comment]
@tyiop794 Assign me this issue if you think it's okay to go ahead.

**Comment by tyiop794** [comment]
I like this idea! I've never used black before, but it seems like specifying the types of methods and variables explicitly would be helpful to other devs unfamiliar with the code. I will assign this issue to you.
