### ISSUE TITLE
Unassigned variable error

### ISSUE THREAD

**Issue by jbecker7** [tyiop794/BibliograPy#5]
When I tried to generate a citation for a book, I got the following error:

UnboundLocalError                         Traceback (most recent call last)
File ~/Documents/GitHub/BibliograPy/main.py:152, in <module>
    150 # Test entry for journal article
    151 if len(sys.argv) == 1:
--> 152     main()
    153 if len(sys.argv) == 2 and (sys.argv[1] == "--usage" or sys.argv[1] == "--help"):
    154     usage()

File ~/Documents/GitHub/BibliograPy/main.py:127, in main()
    125     publisher = input("Publisher?: ")
    126     location = input("Publication location?: ")
--> 127 if digital == "d":
    128     url = input("URL/DOI? (address of website typed into webbrowser): ")
    129 else:

UnboundLocalError: local variable 'digital' referenced before assignment

**Comment by tyiop794** [comment]
I have created separate functions for each source to ask different questions depending on the source chosen; however, these functions are not yet being called by main(). I still have to modify main() so that these functions are called.

The function in this context which needs to be called to main() is book_ask(). I will fix this in an update, unless somebody else would like to take this issue.

**Comment by tyiop794** [comment]
The program should now run as intended. It should be able to export as a PDF.

**Comment by tyiop794** [comment]
Please let me know if there is something I have missed.

**Comment by jbecker7** [comment]
@tyiop794 What argument should I feed into book_ask()? I tried an int at first then an str, but both failed saying object has no attribute 'append'

**Comment by tyiop794** [comment]
You may need to update the version of the repository you currently have, but you should be able to run the program through the main() function without directly interacting with book_ask().

book_ask() requires a sources list which is used to store the sources which will be used in generating the bibliography. If you would like to interact with the classes directly (for testing purposes, for example) you would be better off calling the classes directly and inputting source information through that (for example Article(info) or Book(info)). Information needed can be found in the constructor functions (functions with the name __init__).
